name: Flyway Remote Run
author: 'Ideos Company <https://github.com/ideos>'
description: 'Run flyway commands over ssh'
inputs:
  migrations_path:
    description: 'Path to the migrations files (Relative to project root)'
    required: true
  dbms:
    description: 'One of [ postgres ]'
    required: true
  db_name:
    description: 'Database name'
    required: true
  db_port:
    description: 'Database port'
    required: true
  db_user:
    description: 'Database user'
    required: true
  db_password:
    description: 'Database password'
    required: true
  ssh_key:
    description: SSH private key used to connect to the docker host
    required: true
  ssh_user:
    description: SSH user
    required: true
  ssh_host:
    description: Remote host where docker is running
    required: true
  ssh_port:
    description: 'Remote port to use. (default: 22)'
    required: false
    default: '22'
runs:
  using: docker
  image: Dockerfile
branding:
  icon: database
  color: blue
